[package]
name = "ubu_planning_worker_protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
ubu_core.workspace = true
ubu_planning_core.workspace = true
time.workspace = true

[dev-dependencies]
ubu_planning_cpu.workspace = true
