//! Explicit developer regeneration; no live data, process or framework.
use serde_json::{json, value::RawValue, Value};
use std::{collections::BTreeMap, path::Path};
#[path = "support/week_scale.rs"]
mod week_scale;
use ubu_planning_worker::stage1::*;
fn main() {
    let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/worker");
    let mut fixtures: Vec<Value> = serde_json::from_str(include_str!(
        "../../../fixtures/worker/stage1-requests.json"
    ))
    .unwrap();
    fixtures.extend(week_scale::cases());
    for fixture in &mut fixtures {
        let request = serde_json::from_value(fixture["request"].clone()).unwrap();
        fixture["input"] =
            serde_json::to_value(StageInput::from_request(&request).unwrap()).unwrap();
        fixture["expected"] = serde_json::to_value(reference_output(&request)).unwrap();
    }
    std::fs::write(
        root.join("stage1-goldens.json"),
        format!("{}\n", serde_json::to_string(&fixtures).unwrap()),
    )
    .unwrap();
    let input: StageInput = serde_json::from_value(fixtures[0]["input"].clone()).unwrap();
    let reply = StageReply {
        profile: PROFILE.into(),
        request_id: input.request["request_id"].as_str().unwrap().into(),
        framework_version: "2.6.0+cpu".into(),
        result: serde_json::from_value(fixtures[0]["expected"].clone()).unwrap(),
    };
    let cases=[("stage1",input.message()),("stage1_result",reply.message())].into_iter().map(|(name,frame)|{
        let mut bytes=Vec::new();ubu_planning_worker_protocol::write_frame(&mut bytes,&frame).unwrap();
        json!({"name":name,"frame":frame,"hex":bytes.iter().map(|b|format!("{b:02x}")).collect::<String>()})
    }).collect::<Vec<_>>();
    std::fs::write(
        root.join("stage1-frames.json"),
        format!("{}\n", serde_json::to_string(&cases).unwrap()),
    )
    .unwrap();
    freeze_scoring(&root.join("../planning/golden/scoring-selection-c1.json"));
}

// Preserve untouched numeric literals and historical corpus metadata. Every
// changed expected value comes from the same CPU pipeline that tests certify.
fn freeze_scoring(path: &Path) {
    use ubu_planning_core::{
        legitimization, PlannerStrategy, PlanningRequest, SemiLegitimizationResult,
    };
    use ubu_planning_cpu::CpuStrategy;
    type Fields = BTreeMap<String, Box<RawValue>>;
    let mut corpus: Fields = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    let mut cases: Vec<Fields> = serde_json::from_str(corpus["cases"].get()).unwrap();
    for case in &mut cases {
        let mut request: PlanningRequest = serde_json::from_str(case["request"].get()).unwrap();
        request.n_rollouts = 0;
        let generated = CpuStrategy.generate_candidates(&request);
        let rejected = generated
            .plans
            .iter()
            .filter(|plan| {
                let full = legitimization::full_legitimize(
                    plan,
                    request.affect_profile.as_ref(),
                    request.affect_observation.as_ref(),
                );
                legitimization::semi_legitimize(plan, &request, &full).result
                    == SemiLegitimizationResult::RejectObvious
            })
            .count();
        let response = ubu_planning_core::plan(request, &CpuStrategy);
        let mut candidates = serde_json::to_value(&response.plan_candidates).unwrap();
        for candidate in candidates.as_array_mut().unwrap() {
            candidate["probability_summary"]
                .as_object_mut()
                .unwrap()
                .remove("probability_quality");
        }
        for (name, value) in [
            (
                "expected_generated_candidate_count",
                json!(generated.plans.len()),
            ),
            ("expected_semi_rejected_count", json!(rejected)),
            (
                "expected_selected_candidate_id",
                json!(response.plan_candidates[0].candidate_id),
            ),
            ("expected_plan_candidates", candidates),
        ] {
            if compact_json(case[name].get()) != serde_json::to_vec(&value).unwrap() {
                case.insert(
                    name.into(),
                    serde_json::value::to_raw_value(&value).unwrap(),
                );
            }
        }
    }
    corpus.insert(
        "cases".into(),
        serde_json::value::to_raw_value(&cases).unwrap(),
    );
    corpus.insert("p1b_79_regeneration".into(), serde_json::value::to_raw_value(
        "Occupancy-affected expectations regenerated by freeze_stage1 under UBU-D0171 and UBU-D0301. The kernel_revision and coverage tags identify the historical C-1 corpus baseline; the static-anchor prune case now verifies that overlapping proposals are not generated."
    ).unwrap());
    std::fs::write(
        path,
        format!(
            "{}\n",
            pretty_json(&serde_json::to_string(&corpus).unwrap())
        ),
    )
    .unwrap();
}

// Format outside strings only; parsing untouched floats would lose their
// original literals and needlessly change other byte-exact golden cases.
fn pretty_json(raw: &str) -> String {
    let compact = compact_json(raw);
    let mut output = Vec::new();
    let mut depth = 0;
    let mut quoted = false;
    let mut escaped = false;
    let newline = |output: &mut Vec<u8>, depth: usize| {
        output.push(b'\n');
        output.extend(std::iter::repeat_n(b' ', depth * 2));
    };
    for (index, byte) in compact.iter().copied().enumerate() {
        if quoted {
            output.push(byte);
            if escaped {
                escaped = false;
            } else if byte == b'\\' {
                escaped = true;
            } else if byte == b'"' {
                quoted = false;
            }
            continue;
        }
        match byte {
            b'"' => {
                quoted = true;
                output.push(byte);
            }
            b'{' | b'[' => {
                output.push(byte);
                depth += 1;
                if !matches!(compact.get(index + 1), Some(b'}' | b']')) {
                    newline(&mut output, depth);
                }
            }
            b'}' | b']' => {
                depth -= 1;
                if !matches!(compact.get(index - 1), Some(b'{' | b'[')) {
                    newline(&mut output, depth);
                }
                output.push(byte);
            }
            b',' => {
                output.push(byte);
                newline(&mut output, depth);
            }
            b':' => output.extend_from_slice(b": "),
            _ => output.push(byte),
        }
    }
    String::from_utf8(output).unwrap()
}

fn compact_json(raw: &str) -> Vec<u8> {
    let mut quoted = false;
    let mut escaped = false;
    raw.bytes()
        .filter(|byte| {
            if quoted {
                if escaped {
                    escaped = false;
                } else if *byte == b'\\' {
                    escaped = true;
                } else if *byte == b'"' {
                    quoted = false;
                }
                true
            } else if *byte == b'"' {
                quoted = true;
                true
            } else {
                !byte.is_ascii_whitespace()
            }
        })
        .collect()
}
